root = "."
tmp_dir = "tmp"

[build]
# Use backslashes for Windows paths
cmd = "go build -o .\\tmp\\main.exe .\\cmd\\server"
bin = ".\\tmp\\main.exe"
full_bin = ".\\tmp\\main.exe"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air_errors.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true